# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteid', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='username',
            new_name='authorid',
        ),
    ]
