# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20171119_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='authorid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='points',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='type',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrating',
            name='userrating',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='noteid',
            field=models.PositiveIntegerField(),
        ),
    ]
