# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20171119_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='type',
            field=models.BinaryField(),
        ),
    ]
