# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='noteid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
