# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20171121_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='id',
        ),
        migrations.AlterField(
            model_name='notes',
            name='noteid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
