# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20171121_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='noteid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
