# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20171128_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagNotes',
            fields=[
                ('noteid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
    ]
