# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_tagnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='tagged',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
