# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_notes_tagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='note_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.PositiveIntegerField()),
                ('tag1', models.CharField(max_length=20)),
                ('tag2', models.CharField(max_length=20)),
                ('tag3', models.CharField(max_length=20)),
                ('tag4', models.CharField(max_length=20)),
                ('tag5', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
