# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20171128_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='downvote',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='notes',
            name='upvote',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
