# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20171128_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_user', models.CharField(max_length=20)),
                ('noteid', models.PositiveIntegerField()),
            ],
        ),
    ]
