# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note_meta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='note_meta',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='note_meta',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='note_meta',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='note_meta',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='note_meta',
            name='tag5',
        ),
        migrations.RemoveField(
            model_name='user_meta',
            name='id',
        ),
        migrations.AddField(
            model_name='note_meta',
            name='tags',
            field=models.CharField(default=' ', max_length=5000),
        ),
        migrations.AddField(
            model_name='note_meta',
            name='title',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='user_meta',
            name='titles',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='note_meta',
            name='note_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='tags',
            field=models.CharField(default=' ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='user_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
