# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_auto_20171130_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatSheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheatsheet_title', models.CharField(default=' ', max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cheatsheet',
            name='content',
        ),
        migrations.RemoveField(
            model_name='cheatsheet',
            name='title',
        ),
    ]
