# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_auto_20171130_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatsheet',
            name='position',
        ),
    ]
