# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0023_remove_cheatsheet_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatsheet',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cheatsheet',
            name='note_id',
            field=models.PositiveIntegerField(),
        ),
    ]
